export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  category: "Hair Oils" | "Hair Serums" | "Hair Creams" | "Hair Masks" | "Shampoos" | "Hair Tools";
}

// Fake API function
export const fetchHairProducts = (): Product[] => [
  // ============ Hair Oils ============
  {
    id: 1,
    name: "Olive Oil",
    description: "Moisturizes and reduces breakage",
    price: 10,
    image: "/HairImages/Hair Oils/Olive Oil-1.jpg",
    category: "Hair Oils",
  },
  {
    id: 2,
    name: "Argan Oil",
    description: "Adds shine and nourishment",
    price: 20,
    image: "/HairImages/Hair Oils/Argan Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 3,
    name: "Castor Oil",
    description: "Stimulates growth and strengthens roots",
    price: 15,
    image: "/HairImages/Hair Oils/Castor Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 4,
    name: "Coconut Oil",
    description: "Prevents hair loss and deeply moisturizes",
    price: 10,
    image: "/HairImages/Hair Oils/coconut oil.avif",
    category: "Hair Oils",
  },
  {
    id: 5,
    name: "Jojoba Oil",
    description: "Lightweight, similar to natural oils",
    price: 15,
    image: "/HairImages/Hair Oils/jojoba oil.avif",
    category: "Hair Oils",
  },
  {
    id: 6,
    name: "Rosemary Oil",
    description: "Supports growth and scalp health",
    price: 17,
    image: "/HairImages/Hair Oils/Rosemary Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 7,
    name: "Almond Oil",
    description: "Reduces dryness and frizz",
    price: 15,
    image: "/HairImages/Hair Oils/Almond Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 8,
    name: "Avocado Oil",
    description: "Maintains moisture and shine",
    price: 15,
    image: "/HairImages/Hair Oils/Avocado Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 9,
    name: "Grapeseed Oil",
    description: "Very lightweight, adds shine",
    price: 10,
    image: "/HairImages/Hair Oils/Grapeseed Oil.avif",
    category: "Hair Oils",
  },
  {
    id: 10,
    name: "Apricot Oil",
    description: "Natural softness and shine",
    price: 12,
    image: "/HairImages/Hair Oils/Apricot Oil.avif",
    category: "Hair Oils",
  },

  // ============ Hair Masks ============
  {
    id: 11,
    name: "Repair Mask",
    description: "Repairs damage and strengthens hair",
    price: 18,
    image: "/HairImages/Hair Masks/Repair Mask.webp",
    category: "Hair Masks",
  },
  {
    id: 12,
    name: "Deep Conditioning Mask",
    description: "Moisturizes and adds shine",
    price: 20,
    image: "/HairImages/Hair Masks/Deep Conditioning Mask.webp",
    category: "Hair Masks",
  },
  {
    id: 13,
    name: "Oily Scalp Mask",
    description: "Reduces oil and dandruff",
    price: 10,
    image: "/HairImages/Hair Masks/Oily Scalp Mask.webp",
    category: "Hair Masks",
  },
  {
    id: 14,
    name: "Purple Intensive Mask",
    description: "Treats split ends and frizz",
    price: 18,
    image: "/HairImages/Hair Masks/Purple Mask.webp",
    category: "Hair Masks",
  },

  // ============ Hair Creams ============
  {
    id: 15,
    name: "Deep Moisturizing Cream",
    description: "Treats dryness and split ends",
    price: 18,
    image: "/HairImages/Hair Creams/Deep Moisturizing Cream.jpg",
    category: "Hair Creams",
  },
  {
    id: 16,
    name: "Keratin & Shea Butter Cream",
    description: "Repairs split ends and prevents frizz",
    price: 15,
    image: "/HairImages/Hair Creams/Keratin & Shea Butter Cream.webp",
    category: "Hair Creams",
  },

  // ============ Hair Serums ============
  {
    id: 17,
    name: "Heat Protection Serum",
    description: "Apply before blow-drying",
    price: 10,
    image: "/HairImages/Hair Serums/Heat Protection Serum.webp",
    category: "Hair Serums",
  },
  {
    id: 18,
    name: "Shine & Smooth Serum",
    description: "Adds shine and reduces frizz",
    price: 12,
    image: "/HairImages/Hair Serums/Shine & Smooth Serum.jpg",
    category: "Hair Serums",
  },
  {
    id: 19,
    name: "Serum for Colored Hair",
    description: "Maintains color vibrancy",
    price: 20,
    image: "/HairImages/Hair Serums/Serum for Colored Hair.webp",
    category: "Hair Serums",
  },

  // ============ Shampoos ============
  {
    id: 20,
    name: "Pantene Daily Care Shampoo",
    description: "Gentle daily cleansing for all hair types",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Daily Care - Classic Clean Shampoo.avif",
    category: "Shampoos",
  },
  {
    id: 21,
    name: "Pantene Anti Hair Fall Shampoo",
    description: "Reduces hair fall and strengthens roots",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Anti Hair Fall Shampoo.webp",
    category: "Shampoos",
  },
  {
    id: 22,
    name: "Pantene Anti-Dandruff Shampoo",
    description: "Treats dandruff and cleanses hair",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Anti-Dandruff Shampoo (2-in-1).webp",
    category: "Shampoos",
  },
  {
    id: 23,
    name: "Pantene Smooth & Silky Shampoo",
    description: "Reduces frizz and adds softness",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Smooth & Silky Shampoo.jpg",
    category: "Shampoos",
  },
  {
    id: 24,
    name: "Pantene Moisture Renewal Shampoo",
    description: "Moisturizes dry and brittle hair",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Moisture Renewal Shampoo.avif",
    category: "Shampoos",
  },
  {
    id: 25,
    name: "Pantene Colored Hair Repair Shampoo",
    description: "Maintains color and shine",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Colored Hair Repair Shampoo.avif",
    category: "Shampoos",
  },
  {
    id: 26,
    name: "Pantene Nature Fusion Shampoo",
    description: "Botanical extracts for nourishment",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Nature Fusion Shampoo.webp",
    category: "Shampoos",
  },
  {
    id: 27,
    name: "Pantene Sheer Volume Shampoo",
    description: "Adds volume and thickness",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Sheer Volume Shampoo.avif",
    category: "Shampoos",
  },
  {
    id: 28,
    name: "Pantene Milky Damage Repair Shampoo",
    description: "Repairs damaged hair",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Milky Damage Repair Shampoo.jpg",
    category: "Shampoos",
  },
  {
    id: 29,
    name: "Pantene Micellar Shampoo",
    description: "Gentle cleansing without stripping oils",
    price: 10,
    image: "/HairImages/Pantene Shampoos/Pantene Micellar Gentle Cleansing Shampoo.jpg",
    category: "Shampoos",
  },

  // ============ Hair Tools ============
  {
    id: 30,
    name: "Babyliss Compact Hair Dryer",
    description: "2400W powerful dryer",
    price: 110,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss Compact Hair Dryer (2400 W).jpg",
    category: "Hair Tools",
  },
  {
    id: 31,
    name: "Babyliss Ionic Hair Dryer",
    description: "Reduces frizz with ionic technology",
    price: 90,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss Ionic Hair Dryer (2100 W).jpg",
    category: "Hair Tools",
  },
  {
    id: 32,
    name: "Babyliss 2-in-1 Straightener",
    description: "Straightens and curls hair",
    price: 150,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss ST482E-ST330E 2-in-1 Straightener.jpg",
    category: "Hair Tools",
  },
  {
    id: 33,
    name: "Babyliss Pro Straightener",
    description: "Professional straightener",
    price: 150,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss Pro Professional Straightener.jpg",
    category: "Hair Tools",
  },
  {
    id: 34,
    name: "Babyliss Curl & Wave Trio",
    description: "3 interchangeable heads",
    price: 90,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss Curl & Wave Trio Curling and Wave Device.jpg",
    category: "Hair Tools",
  },
  {
    id: 35,
    name: "Electric Curling Iron",
    description: "Traditional curls",
    price: 50,
    image: "/HairImages/Babyliss hair care and styling products/Electric Curling Iron-Tong.jpg",
    category: "Hair Tools",
  },
  {
    id: 36,
    name: "Babyliss Hot Brush",
    description: "Smooths and dries hair",
    price: 75,
    image: "/HairImages/Babyliss hair care and styling products/Babyliss Hot Brush-Heated Brush.jpg",
    category: "Hair Tools",
  },
  {
    id: 37,
    name: "Air Styler",
    description: "All-in-one styling tool",
    price: 50,
    image: "/HairImages/Babyliss hair care and styling products/Air Styler-Hot Air Brush.jpg",
    category: "Hair Tools",
  },
];
